name: docker
on:
  workflow_dispatch:
  pull_request:
jobs:
  docker-tests:
    runs-on: ubuntu-latest
    env:
      CI: "1"
      EXPO_TUNNEL: "false"
      EXPO_DEVTOOLS_LISTEN_ADDRESS: 0.0.0.0
      EXPO_PUBLIC_API_BASE: http://localhost:8000
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Run tests via docker-compose (deterministic CI)
        run: |
          docker compose -f docker-compose.test.yml up --build --exit-code-from frontend_test
      - name: Upload test reports (if mounted)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-reports
          path: reports/frontend
          if-no-files-found: warn
