name: Frontend Unit Tests
on:
  push:
  pull_request:
jobs:
  test:
    name: Run Jest (React Native / Expo)
    runs-on: ubuntu-latest
    env:
      CI: "1"
      EXPO_PUBLIC_API_BASE: http://localhost:8000
      EXPO_TUNNEL: "false"
      EXPO_DEVTOOLS_LISTEN_ADDRESS: 0.0.0.0
      REACT_NATIVE_PACKAGER_HOSTNAME: 127.0.0.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            frontend/app/package-lock.json
      - name: Install dependencies
        working-directory: frontend/app
        run: npm ci
      - name: Run unit tests (Jest)
        working-directory: frontend/app
        run: |
          npm test -- --ci --runInBand --verbose --coverage
      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: |
            frontend/app/coverage
          if-no-files-found: warn
